---

- name: common-desktop
  src: https://github.com/hackwish/ansible-common-desktop.git
  # version: ubuntu-2004

- name: ohmyzsh
  src: https://github.com/hackwish/ansible-ohmyzsh.git

- name: brew
  src: https://github.com/hackwish/ansible-brew.git

- name: cloudalchemy.node-exporter
  src: cloudalchemy.node-exporter

# - name: bihealth.python3
#   src: bihealth.python3

- name: andrewrothstein.vagrant
  src: andrewrothstein.vagrant

- name: azure-data-studio
  src: https://github.com/hackwish/ansible-azure-data-studio.git

# - name: grzegorznowak.nvm_node
#   src: grzegorznowak.nvm_node

- name: cloud-sql-proxy
  src: https://github.com/hackwish/ansible-cloud-sql-proxy.git

- name: plank
  src: https://github.com/hackwish/ansible-plank.git

- name: tfswitch
  src: https://github.com/hackwish/ansible-tfswitch.git

- name: terragrunt
  src: https://github.com/hackwish/ansible-terragrunt.git

- name: andrewrothstein.sops
  src: andrewrothstein.sops

# - name: andrewrothstein.terraform
#   src: andrewrothstein.terraform

# - name: docker
#   src: https://github.com/hackwish/ansible-docker.git

# - name: rke
#   src: https://github.com/hackwish/ansible-rke.git

# - name: kompose-converter
#   src: https://github.com/hackwish/ansible-kompose-converter.git

# - name: rancher2-cli
#   src: https://github.com/hackwish/ansible-rancher2-cli.git

# - name: capistrano
#   src: https://github.com/hackwish/ansible-capistrano.git

# - name: ibmcloud
#   src: https://github.com/hackwish/ansible-ibmcloud.git
  
# - name: azurecli
#   src: https://github.com/hackwish/ansible-role-azurecli.git

# - name: andrewrothstein.kubernetes-helm
#   src: andrewrothstein.kubernetes-helm

# - name: andrewrothstein.kubectl
#   src: andrewrothstein.kubectl

# - name: wtanaka.gcloud_sdk
#   src: wtanaka.gcloud_sdk

# - name: suzuki-shunsuke.git-lfs-ubuntu
#   src: suzuki-shunsuke.git-lfs-ubuntu

# - name: gantsign.minikube
#   src: gantsign.minikube

# - name: gnagano.ansible_gitflow
#   src: gnagano.ansible_gitflow

# - name: ngetchell.vscode
#   src: ngetchell.vscode

# - name: rgibert.valve_steam
#   src: rgibert.valve_steam

# - name: geerlingguy.packer
#   src: geerlingguy.packer

# - name: andrelohmann.azurecli
#   src: andrelohmann.azurecli
